#!/usr/bin/env node
/**
 * Writes src/tokens.ts — every `--color-*` token in src/styles/theme.css as a plain value,
 * per theme — so places that cannot read a CSS variable can still take their colours from the
 * design system: a PDF renderer, an HTML email, a non-Tailwind site's theme.
 *
 * theme.css stays the single source. This file is generated from it, never edited, and
 * `build:lib` regenerates it before bundling, so a published build cannot carry a stale copy.
 * test/tokens.test.ts fails when the committed file differs from what this produces.
 *
 *   dark  = @theme + @theme static, with `.dark` applied (the default theme)
 *   light = @theme + @theme static, with `.light` applied
 *
 * `var(--color-…)` references are resolved within the theme, so every value is literal CSS
 * (a hex, or an rgb() for the translucent table inks). Anything else is copied verbatim.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const THEME = join(ROOT, "src/styles/theme.css");
const OUT = join(ROOT, "src/tokens.ts");

/** The body of the block opened by `opener` (e.g. ".light {"), up to its closing brace. */
function block(css, opener) {
  const start = css.indexOf(opener);
  if (start === -1) throw new Error(`theme.css: no "${opener}" block`);
  const rest = css.slice(start + opener.length);
  return rest.slice(0, rest.indexOf("\n}"));
}

/** `--color-<name>: <value>;` declarations, in source order, comments stripped. */
function declarations(body) {
  const clean = body.replace(/\/\*[\s\S]*?\*\//g, "");
  return Array.from(clean.matchAll(/--color-([a-z0-9-]+)\s*:\s*([^;]+);/g), (m) => [
    m[1],
    m[2].trim(),
  ]);
}

function resolveTheme(entries) {
  const map = new Map(entries);
  const resolve = (value, seen) =>
    value.replace(/var\(--color-([a-z0-9-]+)\)/g, (_, name) => {
      if (seen.has(name)) throw new Error(`theme.css: --color-${name} refers to itself`);
      if (!map.has(name)) throw new Error(`theme.css: var(--color-${name}) is not declared`);
      return resolve(map.get(name), new Set([...seen, name]));
    });
  return Object.fromEntries([...map].map(([name, value]) => [name, resolve(value, new Set([name]))]));
}

export function colorTokensFrom(css) {
  const base = [...declarations(block(css, "@theme {")), ...declarations(block(css, "@theme static {"))];
  return {
    dark: resolveTheme([...base, ...declarations(block(css, ".dark {"))]),
    light: resolveTheme([...base, ...declarations(block(css, ".light {"))]),
  };
}

export function tokensSource(css) {
  const tokens = colorTokensFrom(css);
  const theme = (values) =>
    Object.entries(values)
      .map(([name, value]) => `    ${JSON.stringify(name)}: ${JSON.stringify(value)},`)
      .join("\n");
  return `/**
 * GENERATED by scripts/generate-tokens.mjs from src/styles/theme.css. Do not edit:
 * change theme.css and run \`pnpm tokens:generate\` (build:lib does it too).
 *
 * Every colour token as a plain CSS value, per theme, for places that cannot read a CSS
 * variable: a PDF renderer, an HTML email, a site that does not use Tailwind. In a browser
 * app, use the utilities and \`var(--color-…)\` from the stylesheet instead, so a theme
 * switch reaches them.
 *
 *   import { colorTokens } from "@codelittinc/carbon-design-system/tokens";
 *   colorTokens.light["text-primary"]; // "#18181b"
 */
export const colorTokens = {
  dark: {
${theme(tokens.dark)}
  },
  light: {
${theme(tokens.light)}
  },
} as const;

export type ColorTheme = keyof typeof colorTokens;
export type ColorToken = keyof (typeof colorTokens)["dark"];
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT, tokensSource(readFileSync(THEME, "utf8")));
  console.log(`wrote ${OUT}`);
}
